server:
  port: 8030
spring:
  application:
    name: chen
  datasource:
    url: jdbc:sqlserver://localhost:1433;DatabaseName=xuesheng
    username: sa
    password: 123456a
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
  jpa:
      show-sql: true
      properties:
        hibernate:
          format_sql: true
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
zuul:
  routes:
    proft: /P/**