server:
  port: 8762
spring:
  application:
    name: nativeConfigServer
  profiles:
    active: native
  cloud:
    config:
      server:
        native:
          search-locations:  classpath:/shared
  datasource:
    url: jdbc:sqlserver://localhost:1433;DatabaseName=xuesheng
    username: sa
    password: 123456a
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true