server:
  port: 8761
eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://localhost:8761/eureka/
spring:
  datasource:
    url: jdbc:sqlserver://localhost:1433;DatabaseName=xuesheng
    username: sa
    password: 123456a
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver