server:
  port: 8040
spring:
  application:
    name: achen
  datasource:
    username: sa
    password: 123456a
    url: jdbc:sqlserver://localhost:1433;DatabaseName=xuesheng
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true